### PR TITLE
Require verification for 20% of new accounts

### PR DESCRIPTION
**Pull request by duogenesis**

### CODE REVIEW

**Comment by wiki-me** [comment]
I really dislike this, part of whats great about talking to people online is that you can be anonymouse and that helps to talk more freely instead of being busy with impression management like you need to in real life. Also i saw  people trick the verification algorithm by not showing there faces, maybe unintetionally (see for example "kye" , or "noelle 25").

I suggest as an alternative to add a filter for verified profiles , and add a getting started tour that will show the option of filters (assuming most people don't discover that option, i mentioned before this hypothesis could be tested).

**Comment by duogenesis** [comment]
I don't like it either, but I need to operate in the world that exists
rather than the one I'd like to exist. The feedback I've gotten from many
women is that harassment tends to come from unverified users. Other women
have voiced general unease about not knowing who they're talking to. I
realize that not all female users feel this way, and not all male users
harass women. I also expect that some male users will criticize me of
sexism for pandering to women. However, I also know that men want a good
gender ratio---That can be improved by improving the experience of women.

Whether this change legitimately does improve the experience of women is
hard to say without trying it and checking how the change affects retention.

I think a better possible solution to try would be to place restrictions on
the number of messages unverified users can send per day. Though this PR is
quicker so I'm going with this for now.

It's worth mentioning that about one in three men are verified now. So
having one in five profiles require verification by default doesn't seem so
unreasonable to me.

I agree that a tutorial would be useful for onboardees, to explain the
defaults.

**Comment by duogenesis** [comment]
> why not build a filter in the inbox that women can configure to not show unverified users

By default that feature can be on or off.

If it's on by default, that'd exclude 77% of male profiles on a dating app with 20k active users.

If it's off by default, we're relying on women either to anticipate that they'll get harassed by unverified members and turn the filter on for that reason; or to get harassed and conclude that it was because they made the mistake of leaving that filter off, so they should therefore turn it on rather than deleting their account.

>maybe add more criterions like age of account

I think that'd be effective for reducing harassment; A disproportionate amount of reports seem to come from new accounts. But it might also negatively effect the retention of legitimate users. That might be fine if the user can override that timeout period by doing something that takes a few minutes, like getting verified (or even paying a small one-off fee).

>Now that i think about it this might be a good blog post, what are the predictors and best predictor of a user getting reported.

It's hard to analyse because the GDPR prevents us from keeping the data of users who were banned. The data we have are on users who were reported but never banned.

**Comment by wiki-me** [comment]
> If it's on by default, that'd exclude 77% of male profiles on a dating app with 20k active users.

I am sure some of them will turn it off, but besides that doesn't your argument about improving gender ratio will apply? . from what i read the biggest problem with dating websites is not the amount of interactions but their quality. with women reporting they are getting overloaded with messages (like that joke about getting 100 messages saying "hi").

> If it's off by default, we're relying on women either to anticipate that they'll get harassed by unverified members and turn the filter on for that reason; or to get harassed and conclude that it was because they made the mistake of leaving that filter off, so they should therefore turn it on rather than deleting their account.

It think there is definitely a room for some guide on how to use the website, a dating website i once tested had  a thing where it would show a safety tip every time you visited a profile, a "tip of the day" type thing could also be useful and which could be turned off. stuff from [how to get more replies](https://duolicious.app/blog/how-to-get-more-replies-on-dating-apps/) could also be used.

> It's hard to analyse because the GDPR prevents us from keeping the data of users who were banned. The data we have are on users who were reported but never banned.

europeans ...

Couldn't this be tested only non european users?

I think there should be a pretty good correlation between women reporting something and anti social behavior, or maybe do some analysis before banning the user?

**Comment by duogenesis** [comment]
>I am sure some of them will turn it off, but besides that doesn't your argument about improving gender ratio will apply?

The gender ratio of verified active accounts is currently about 18:1, vs 8:1 for all active accounts.

>Couldn't this be tested only non european users?

In principle, but imagine having different data deletion logic for different countries, which you have to change per region as the laws do. The task is within reach for a big company, but not for a dating app run by one person.

>I think there should be a pretty good correlation between women reporting something and anti social behavior

Yeah, probably

**Comment by wiki-me** [comment]
> The gender ratio of verified active accounts is currently about 18:1, vs 8:1 for all active accounts.

Isn't the gender ratio different and better toward men when the goal is marriage and finding friends? (according to your [blog](https://duolicious.app/blog/the-gender-gap-in-dating-among-4channers/) post). I think gender ratio should be reported while being divided according to the goals. if i am looking for friends why should i care a lot of men are looking for one night stands? .if the website is used for short term dating i am fairly confident there will be a lot more men then women. Plus if some users are more conscientiousness i don't see a reason not to make women have the ability to give them a competitive advantage. it seems more fair plus if they are satisfied they are probably more likely to contribute to duolicious.

**Pull request merged**
